/******************Block Comment***********************
 * Sean Berlin
 * Program Description: The mathematician Euclid proved that there is an infinite number of prime numbers. 
 *                      One of the greatest challenges to mathematicians was to find a formula that would generate all the prime numbers. 
 *                      It has been purported that all prime numbers will be either one less than or one greater than a multiple of 6. 
 *                      That is all primes will all be either when N mod 6 equals 1 or 5, however not every number generated by this condition will be prime. 
 *                      Write a program to test this theory for all numbers <=500.
 * 
 * Required statements: output, loop control, decision making, function
 * 
 * Sample Copy:
 * Prime numbers found by this conjecture...
 * 7 11 13 17 19 23 29 31 37 41
 * 43 47 53 59 61 67 71 73 79 83
 * 89 97 101 103 107 109 113 127 131 137
 * 139 149 151 157 163 167 173 179 181 191
 * 193 197 199 211 223 227 229 233 239 241
 * 251 257 263 269 271 277 281 283 293 307
 * 311 313 317 331 337 347 349 353 359 367
 * 373 379 383 389 397 401 409 419 421 431
 * 433 439 443 449 457 461 463 467 479 487
 * 
 * ***********************************************
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Mythical_6
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Prime Numbers found by this conjecture...");
            Console.WriteLine();
            for (int num = 7; num <= 500; num++)
            {
                if (num % 6 == 1 || num % 6 == 5) //does conjecture
                {
                    //num = num % 6;
                    //then will check if num is prime, if prime then prints it
                    int i, m = 0, flag = 0;
                    m = num / 2;
                    for (i = 2; i <= m; i++)
                    {
                        if (num % i == 0)
                        {
                            flag = 1;
                            break;
                        }
                    }
                    if (flag == 0)
                    {
                        Console.Write("\t{0}", num);
                    }
                }
            }
            Console.ReadLine();
        }
    }
}
